### ISSUE TITLE
Write E2E and UI tests using Cypress

### ISSUE THREAD

**Issue by emigiusto** [emicludo/DevOps-group_s#78]

**Comment by emigiusto** [comment]
Use puppeteer? Similar to Selenium, compatible with Node.js

**Comment by ingrid-mc** [comment]
The Mocha framework, which we have started using, does support front-end testing as well

**Comment by emigiusto** [comment]
I think that something like Puppeteer or Selenium will be needed at some point because I'm guessing that we will need a running instance of a browser like in Henge's description. But I might misunderstand the task.

**Comment by ingrid-mc** [comment]
Yes, if that's a requirement, we can use another framework if Mocha doesn't support it. Cypress is also really cool and intuitive and supports that.
